#TODO:...To calculate the life in weeks.....
#?...we will just take the input from the users and we will print thei remaining weeks in life..
age = input("What is your current age? ")
#!....Always remember to convert age as integer.....
age_as_int = int(age)
#?..we will assume if the users is goinn to live for 90 yrs then how many weeks theire...
years_remaining = 60 - age_as_int
days_remaining = years_remaining * 365
weeks_remaining = years_remaining * 52
months_remaining = years_remaining * 12
#!...by using F-string we will print the result...
message = (f"You have {days_remaining} days, {weeks_remaining } weeks, and {months_remaining } months left.")
print(message)
